package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * AbstractWell is the base class for Well's and WellMaps.
 * @author mford
 */
public abstract class AbstractWell<T extends AbstractWell> extends BaseEntity {

    private Long id;

    /**
     * Coordinate identifies the row,col for the Well
     */
    private Coordinate coordinate;

    private Set<Label> labels;

    /**
     * The well type tells us if this is a regular measured dose of a compound
     * or a special well like a positive, negative control or empty.
     */
    @NotNull
    private WellType type;

    public AbstractWell() {}

    public AbstractWell(int row, int col) {
        setCoordinate(new Coordinate(row, col));
    }

    public AbstractWell(Coordinate coord) {
        setCoordinate(coord);
    }

    public T withLabel(String name, String value) {
        if (labels==null) {
            labels = new LinkedHashSet<>();
        }
        labels.add(new Label(name, value));
        //noinspection unchecked
        return (T) this;
    }

    public T withId(final Long id) {
        this.id = id;
        //noinspection unchecked
        return (T) this;
    }

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public T setId(Long id) {
        this.id = id;
        return (T) this;
    }

    @Generated("generated by IDE")
    public Coordinate getCoordinate() {
        return coordinate;
    }

    @Generated("generated by IDE")
    public T setCoordinate(Coordinate coordinate) {
        this.coordinate = coordinate;
        return (T) this;
    }

    @Generated("generated by IDE")
    public Set<Label> getLabels() {
        return labels;
    }

    @Generated("generated by IDE")
    public T setLabels(Set<Label> labels) {
        this.labels = labels;
        return (T) this;
    }

    @Generated("generated by IDE")
    public WellType getType() {
        return type;
    }

    @Generated("generated by IDE")
    public T setType(WellType type) {
        this.type = type;
        return (T) this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AbstractWell that = (AbstractWell) o;

        if (!coordinate.equals(that.coordinate)) return false;

        return true;
    }

    @Override
    @Generated(value = "generated by IDE")
    public int hashCode() {
        return coordinate.hashCode();
    }

    public String getContentsLabel() {

        if (getType() == WellType.EMPTY) return null;

        // look for a label w/ the name "contents"
        for(Label label : getLabels()) {
            if (label.getName().equalsIgnoreCase("contents")) {
                return label.getValue();
            }
        }
        // if not found, return the first one?
        return getLabels().iterator().next().getValue();
    }
}
