package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class AbstractFitParameter<T extends AbstractFitParameter> extends BaseEntity {

    private Long id;

    private FitEquation fitEquation = FitEquation.HILLEQUATION;


    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public T setId(Long id) {
        this.id = id;
        return (T) this;
    }

    @Generated("generated by IDE")
    public FitEquation getFitEquation() {
        return fitEquation;
    }

    @Generated("generated by IDE")
    public T setFitEquation(FitEquation fitEquation) {
        this.fitEquation = fitEquation;
        return (T) this;
    }
}
