package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Embeddable;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author mford
 */
@Embeddable
public class Amount {
    /**
     * The number of the compound to be put into the well
     */
    @NotNull
    @Min(0)
    private Double number = 0d;

    /**
     * The units used to measure how much of the compound is in the well
     */
    @NotNull
    private DoseUnit units = DoseUnit.MILLIMOLAR;

    @SuppressWarnings("unused")
    public Amount() {}

    public Amount(double number, DoseUnit units) {
        this.number = number;
        this.units = units;
    }

    @Generated("generated by IDE")
    public Double getNumber() {
        return number;
    }

    @Generated("generated by IDE")
    public Amount setNumber(Double number) {
        this.number = number;
        return this;
    }

    @Generated("generated by IDE")
    public DoseUnit getUnits() {
        return units;
    }

    @Generated("generated by IDE")
    public Amount setUnits(DoseUnit units) {
        this.units = units;
        return this;
    }

    public Amount dilute(Double dilutionFactor) {
        return new Amount(number/dilutionFactor, units);
    }
}
