package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Entity for a named compound within our domain
 *
 * @author mford
 */
@Entity
public class Compound extends BaseEntity {

    /**
     * Primary key is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Compound names must be unique within our system
     */
    @Column(unique = true)
    private String name;

    public Compound() {}

    public Compound(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Compound withId(final Long id) {
        this.id = id;
        return this;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Compound withName(final String name) {
        this.name = name;
        return this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public String toString() {
        return "Compound{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
