package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * Entity for a named compound within our domain
 *
 * @author mford
 */
public class Compound extends BaseEntity {

    private Long id;

    /**
     * Compound names must be unique within our system
     */
    private String name;

    public Compound() {}

    public Compound(String name) {
        this.name = name;
    }

    public Compound(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Compound withId(final Long id) {
        this.id = id;
        return this;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Compound withName(final String name) {
        this.name = name;
        return this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public String toString() {
        return "Compound{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
