package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * Entity for a named compound within our domain
 *
 * @author mford
 */
public class Compound extends BaseEntity {

    private Long id;

    /**
     * Compound names must be unique within our system
     */
    private String name;

    public Compound() {}

    public Compound(String name) {
        this.name = name;
    }

    public Compound(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public Compound setId(Long id) {
        this.id = id;
        return this;
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public Compound setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public String toString() {
        return "Compound{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    @Generated(value = "generated by IDE")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Compound compound = (Compound) o;

        return name.equals(compound.name);

    }

    @Override
    @Generated(value = "generated by IDE")
    public int hashCode() {
        return name.hashCode();
    }
}
