package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Embeddable;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author mford
 */
@Embeddable
public class Coordinate extends BaseEntity {
    @NotNull
    @Min(0)
    private Integer row;
    @NotNull @Min(0)
    private Integer col;

    public Coordinate() {}

    public Coordinate(int row, int col) {
        this.row = row;
        this.col = col;
    }

    @Generated(value = "generated by IDE")
    public Integer getCol() {
        return col;
    }

    @Generated(value = "generated by IDE")
    public void setCol(Integer col) {
        this.col = col;
    }

    @Generated(value = "generated by IDE")
    public Integer getRow() {
        return row;
    }

    @Generated(value = "generated by IDE")
    public void setRow(Integer row) {
        this.row = row;
    }

    @Override
    @Generated(value = "generated by IDE")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Coordinate that = (Coordinate) o;

        if (!col.equals(that.col)) return false;
        if (!row.equals(that.row)) return false;

        return true;
    }

    @Override
    @Generated(value = "generated by IDE")
    public int hashCode() {
        int result = row.hashCode();
        result = 31 * result + col.hashCode();
        return result;
    }
}
