package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Embeddable;

/**
 * @author alan orcharton
 */
@Embeddable
public class CurveFitPoint  {

    private Integer sequenceNumber;
    private Double x;
    private Double y;

    public CurveFitPoint() {}

    public CurveFitPoint(Integer sequenceNumber){
        super();
        this.sequenceNumber = sequenceNumber;
    }

    @Generated("generated by IDE")
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    @Generated("generated by IDE")
    public CurveFitPoint setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    @Generated("generated by IDE")
    public Double getX() {
        return x;
    }

    @Generated("generated by IDE")
    public CurveFitPoint setX(Double x) {
        this.x = x;
        return this;
    }

    @Generated("generated by IDE")
    public Double getY() {
        return y;
    }

    @Generated("generated by IDE")
    public CurveFitPoint setY(Double y) {
        this.y = y;
        return this;
    }
}
