package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class CurveFitPoint extends AbstractPoint<CurveFitPoint> {

    private Integer sequenceNumber;

    public CurveFitPoint(){};
    public CurveFitPoint(Integer sequenceNumber){
        super();
        this.sequenceNumber = sequenceNumber;
    }


    @Generated("generated by IDE")
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    @Generated("generated by IDE")
    public CurveFitPoint setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }
}
