package edu.harvard.we99.domain;

import edu.harvard.we99.domain.results.DoseResponseResult;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class ExperimentPoint extends AbstractPoint<ExperimentPoint> {


    private Plate associatedPlate;
    private Well associatedWell;




    public ExperimentPoint(){}
    public ExperimentPoint(Plate plate, Well well){
        super();
        this.associatedPlate = plate;
        this.associatedWell = well;

    }



    /**
     * Get the concentration of the compound form the well
     * todo: Have the Dose return the full amount handling the units then log10
     * @param compound the compound to match
     * @return
     */
    /*
    private Double calcXLogConcentration(Compound compound){

        Double compoundDose = 0.0;
        Set<Dose> doses = this.associatedWell.getContents();
        for(Dose d : doses){
            if (d.getCompound().equals(compound)){
                compoundDose = d.getAmount().getNumber();
            }
        }
        return compoundDose;

    }

    private Double calcYPercentEffect(){

        List<Sample> samples = this.associatedWellValues.getSamples();
        Sample sample = samples.get(0);
        return sample.getNormalized();

    }
     */

    @Generated("generated by IDE")
    public Well getAssociatedWell() {
        return associatedWell;
    }

    @Generated("generated by IDE")
    public ExperimentPoint setAssociatedWell(Well associatedWell) {
        this.associatedWell = associatedWell;
        return this;
    }


    @Generated("generated by IDE")
    public Plate getAssociatedPlate() {
        return associatedPlate;
    }

    @Generated("generated by IDE")
    public ExperimentPoint setAssociatedPlate(Plate associatedPlate) {
        this.associatedPlate = associatedPlate;
        return this;
    }

    @Generated("generated by IDE")
    public DoseResponseResult getAssociatedDoseResponseResult() {
        return associatedDoseResponseResult;
    }

    @Generated("generated by IDE")
    public ExperimentPoint setAssociatedDoseResponseResult(DoseResponseResult associatedDoseResponseResult) {
        this.associatedDoseResponseResult = associatedDoseResponseResult;
        return this;
    }
}
