package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Embeddable;

/**
 * @author alan orcharton
 */
@Embeddable
public class FitParameter {

    private Double value;

    private String name;

    private ParameterStatus status = ParameterStatus.FLOAT;

    public FitParameter(){}

    public FitParameter(String name, double value, ParameterStatus status){
        this.name = name;
        this.value = value;
        this.status = status;
    }

    @Generated("generated by IDE")
    public Double getValue() {
        return value;
    }

    @Generated("generated by IDE")
    public FitParameter setValue(Double value) {
        this.value = value;
        return this;
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public FitParameter setName(String name) {
        this.name = name;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getStatus() {
        return status;
    }

    @Generated("generated by IDE")
    public FitParameter setStatus(ParameterStatus status) {
        this.status = status;
        return this;
    }
}
