package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class HillFitParameter extends AbstractFitParameter<HillFitParameter> {

    private Double top;
    private Double bottom;
    private Double logEC50;
    private Double slope;

    private ParameterStatus topStatus = ParameterStatus.FLOAT;
    private ParameterStatus bottomStatus = ParameterStatus.FLOAT;
    private ParameterStatus logEC50Status = ParameterStatus.FLOAT;
    private ParameterStatus slopeStatus = ParameterStatus.FLOAT;


    @Generated("generated by IDE")
    public Double getTop() {
        return top;
    }

    @Generated("generated by IDE")
    public HillFitParameter setTop(Double top) {
        this.top = top;
        return this;
    }

    @Generated("generated by IDE")
    public Double getBottom() {
        return bottom;
    }

    @Generated("generated by IDE")
    public HillFitParameter setBottom(Double bottom) {
        this.bottom = bottom;
        return this;
    }

    @Generated("generated by IDE")
    public Double getLogEC50() {
        return logEC50;
    }

    @Generated("generated by IDE")
    public HillFitParameter setLogEC50(Double logEC50) {
        this.logEC50 = logEC50;
        return this;
    }

    @Generated("generated by IDE")
    public Double getSlope() {
        return slope;
    }

    @Generated("generated by IDE")
    public HillFitParameter setSlope(Double slope) {
        this.slope = slope;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getTopStatus() {
        return topStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameter setTopStatus(ParameterStatus topStatus) {
        this.topStatus = topStatus;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getBottomStatus() {
        return bottomStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameter setBottomStatus(ParameterStatus bottomStatus) {
        this.bottomStatus = bottomStatus;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getLogEC50Status() {
        return logEC50Status;
    }

    @Generated("generated by IDE")
    public HillFitParameter setLogEC50Status(ParameterStatus logEC50Staus) {
        this.logEC50Status = logEC50Staus;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getSlopeStatus() {
        return slopeStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameter setSlopeStatus(ParameterStatus slopeStatus) {
        this.slopeStatus = slopeStatus;
        return this;
    }
}
