package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import java.util.ArrayList;
import java.util.List;

/**
 * @author mford
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class ImportedPlateMap {
    private PlateMap plateMap;
    private List<PlateType> matchingPlateTypes = new ArrayList<>();

    @SuppressWarnings("UnusedDeclaration")
    public ImportedPlateMap() {}

    public ImportedPlateMap(PlateMap plateMap, List<PlateType> list) {
        this.plateMap = plateMap;
        this.matchingPlateTypes = list;
    }

    @Generated("generated by IDE")
    public PlateMap getPlateMap() {
        return plateMap;
    }

    @Generated("generated by IDE")
    public ImportedPlateMap setPlateMap(PlateMap plateMap) {
        this.plateMap = plateMap;
        return this;
    }

    @Generated("generated by IDE")
    public List<PlateType> getMatchingPlateTypes() {
        return matchingPlateTypes;
    }

    @Generated("generated by IDE")
    public ImportedPlateMap setMatchingPlateTypes(List<PlateType> matchingPlateTypes) {
        this.matchingPlateTypes = matchingPlateTypes;
        return this;
    }
}
