package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import java.util.ArrayList;
import java.util.List;

/**
 * @author mford
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class ImportedPlateMap {
    private PlateMap plateMap;
    private List<PlateType> matchingPlateTypes = new ArrayList<>();

    public ImportedPlateMap() {}

    public ImportedPlateMap(PlateMap plateMap, List<PlateType> list) {
        this.plateMap = plateMap;
        this.matchingPlateTypes = list;
    }

    @Generated(value = "generated by IDE")
    public List<PlateType> getMatchingPlateTypes() {
        return matchingPlateTypes;
    }

    @Generated(value = "generated by IDE")
    public void setMatchingPlateTypes(List<PlateType> matchingPlateTypes) {
        this.matchingPlateTypes = matchingPlateTypes;
    }

    @Generated(value = "generated by IDE")
    public PlateMap getPlateMap() {
        return plateMap;
    }

    @Generated(value = "generated by IDE")
    public void setPlateMap(PlateMap plateMap) {
        this.plateMap = plateMap;
    }
}
