package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author mford
 */
public class Label extends BaseEntity {
    private Long id;
    private String name;
    private String value;

    public Label() {}
    public Label(String name) {
        this.name = name;
    }
    public Label(String name, String value) {
        this.name = name;
        this.value = value;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public String getValue() {
        return value;
    }

    @Generated(value = "generated by IDE")
    public void setValue(String value) {
        this.value = value;
    }
}
