package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * Labels are simple name/value pairs that can be applied to wells
 *
 * @author mford
 */
public class Label extends BaseEntity {
    // todo - I don't think we need to have the id here. I think the labels are dropped and recreated on every update
    private Long id;
    private String name;
    private String value;

    public Label() {}
    public Label(String name) {
        this.name = name;
    }
    public Label(String name, String value) {
        this.name = name;
        this.value = value;
    }

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public Label setId(Long id) {
        this.id = id;
        return this;
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public Label setName(String name) {
        this.name = name;
        return this;
    }

    @Generated("generated by IDE")
    public String getValue() {
        return value;
    }

    @Generated("generated by IDE")
    public Label setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Label label = (Label) o;

        return name.equals(label.name);

    }

    @Override
    @Generated(value = "generated by IDE")
    public int hashCode() {
        return name.hashCode();
    }
}
