package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

/**
 * Defines the type of physical plate we're dealing with. These plates are
 * assumed to be rectangular. We can infer the shape and size from the rows/cols.
 *
 * @author mford
 */
@Entity
public class PlateType extends BaseEntity {
    /**
     * The primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Embedded
    @NotNull
    private PlateDimension dim;

    /**
     * The manufacturer of the plate
     *
     * todo - could model this as an entity as well
     */
    @NotNull
    private String manufacturer;

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getManufacturer() {
        return manufacturer;
    }

    @Generated(value = "generated by IDE")
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Generated(value = "generated by IDE")
    public PlateType withManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateDimension getDim() {
        return dim;
    }

    @Generated(value = "generated by IDE")
    public void setDim(PlateDimension dim) {
        this.dim = dim;
    }

    @Generated(value = "generated by IDE")
    public PlateType withDim(final PlateDimension dim) {
        this.dim = dim;
        return this;
    }


}
