package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

/**
 * Defines the type of physical plate we're dealing with. These plates are
 * assumed to be rectangular. We can infer the shape and size from the rows/cols.
 *
 * @author mford
 */
public class PlateType extends BaseEntity {
    private Long id;

    /**
     * name of the plate
     */
    @NotNull
    private String name;

    /**
     * Optional description for the plate.
     */
    private String description;

    @NotNull
    private PlateDimension dim;

    /**
     * The manufacturer of the plate
     */
    @NotNull
    private String manufacturer;

    /**
     * Link to the manufacturer's website to order plates of this type.
     */
    private String orderLink;

    @Generated(value = "generated by IDE")
    public String getDescription() {
        return description;
    }

    @Generated(value = "generated by IDE")
    public void setDescription(String description) {
        this.description = description;
    }

    @Generated(value = "generated by IDE")
    public String getOrderLink() {
        return orderLink;
    }

    @Generated(value = "generated by IDE")
    public void setOrderLink(String orderLink) {
        this.orderLink = orderLink;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getManufacturer() {
        return manufacturer;
    }

    @Generated(value = "generated by IDE")
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Generated(value = "generated by IDE")
    public PlateType withManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateDimension getDim() {
        return dim;
    }

    @Generated(value = "generated by IDE")
    public void setDim(PlateDimension dim) {
        this.dim = dim;
    }

    @Generated(value = "generated by IDE")
    public PlateType withDim(final PlateDimension dim) {
        this.dim = dim;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withLink(final String link) {
        this.orderLink = link;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withName(final String name) {
        this.name = name;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withDescription(final String description) {
        this.description = description;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withId(final Long id) {
        this.id = id;
        return this;
    }


}
