package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * Defines the type of physical plate we're dealing with. These plates are
 * assumed to be rectangular. We can infer the shape and size from the rows/cols.
 *
 * @author mford
 */
@Entity
public class PlateType extends BaseEntity {
    /**
     * The primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The number of rows in the plate. Must be at least 1
     */
    @Min(1)
    private int rows;

    /**
     * The number of cols in the plate. Must be at least 1
     */
    @Min(1)
    private int cols;

    /**
     * The manufacturer of the plate
     *
     * todo - could model this as an entity as well
     */
    @NotNull
    private String manufacturer;

    @Generated(value = "generated by IDE")
    public int getCols() {
        return cols;
    }

    @Generated(value = "generated by IDE")
    public void setCols(int cols) {
        this.cols = cols;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getManufacturer() {
        return manufacturer;
    }

    @Generated(value = "generated by IDE")
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Generated(value = "generated by IDE")
    public int getRows() {
        return rows;
    }

    @Generated(value = "generated by IDE")
    public void setRows(int rows) {
        this.rows = rows;
    }

    @Generated(value = "generated by IDE")
    public PlateType withCols(final int cols) {
        this.cols = cols;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateType withRows(final int rows) {
        this.rows = rows;
        return this;
    }
}
