package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class PlotPoint extends BaseEntity {

   private Double x,y;

    @SuppressWarnings("unused") // needed for jaxb
    public PlotPoint(){
        this.x = 0.0;
        this.y = 0.0;

    }

    public PlotPoint(Double x, Double y){
        this.x =x;
        this.y =y;
    }


    @Generated("generated by IDE")
    public Double getX() {
        return x;
    }

    @Generated("generated by IDE")
    public void setX(Double x) {
        this.x = x;
    }


    @Generated("generated by IDE")
    public Double getY() {
        return y;
    }

    @Generated("generated by IDE")
    public void setY(Double y) {
        this.y = y;
    }
}
