package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

/**
 * A protocol is a set of rules/procedures that govern the experiment. These
 * are defined externally from our system and are referenced here as a simple
 * label.
 *
 * @author mford
 */
public class Protocol extends BaseEntity {
    private Long id;

    /**
     * Name of the protocol
     */
    @NotNull
    private String name;

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Protocol withId(final Long id) {
        this.id = id;
        return this;
    }

    @Generated(value = "generated by IDE")
    public Protocol withName(final String name) {
        this.name = name;
        return this;
    }


}
