package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

/**
 * @author markford
 */
public class WellLabelMapping extends BaseEntity {
    @NotNull
    private String label;
    @NotNull
    private Integer count;
    private WellType wellType;
    private Dose dose;
    private Double dilutionFactor;
    private Integer replicates;

    @Generated("generated by IDE")
    public String getLabel() {
        return label;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setLabel(String label) {
        this.label = label;
        return this;
    }

    @Generated("generated by IDE")
    public Integer getCount() {
        return count;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setCount(Integer count) {
        this.count = count;
        return this;
    }

    @Generated("generated by IDE")
    public WellType getWellType() {
        return wellType;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setWellType(WellType wellType) {
        this.wellType = wellType;
        return this;
    }

    @Generated("generated by IDE")
    public Dose getDose() {
        return dose;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setDose(Dose dose) {
        this.dose = dose;
        return this;
    }

    @Generated("generated by IDE")
    public Double getDilutionFactor() {
        return dilutionFactor;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setDilutionFactor(Double dilutionFactor) {
        this.dilutionFactor = dilutionFactor;
        return this;
    }

    @Generated("generated by IDE")
    public Integer getReplicates() {
        return replicates;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setReplicates(Integer replicates) {
        this.replicates = replicates;
        return this;
    }
}
