package edu.harvard.we99.domain;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;
import java.util.ArrayList;
import java.util.List;

/**
 * @author markford
 */
public class WellLabelMapping extends BaseEntity {
    @NotNull
    private String label;
    @NotNull
    private Integer count;
    private WellType wellType;
    private Dose dose;
    private Double dilutionFactor;
    private Integer replicates;

    @XmlTransient
    List<Dose> doses;

    public Dose take() {
        if (doses == null) {
            initDoses();
        }
        if (doses.isEmpty()) {
            return null;
        }
        return doses.remove(0);
    }

    // protected for unit tests
    protected void initDoses() {
        doses = new ArrayList<>();
        Dose d = dose;
        double rep = replicates==null?0:replicates;
        for(int i=0; i<count; i++) {
            if (rep >0 && ((i%rep)==0 && i>0) || (rep == 0 && i>0)) {
                if (dilutionFactor != null) {
                    d = d.dilute(dilutionFactor);
                }
            }
            doses.add(new Dose(d.getCompound(), d.getAmount()));
        }
    }

    @Generated("generated by IDE")
    public String getLabel() {
        return label;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setLabel(String label) {
        this.label = label;
        return this;
    }

    @Generated("generated by IDE")
    public Integer getCount() {
        return count;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setCount(Integer count) {
        this.count = count;
        return this;
    }

    @Generated("generated by IDE")
    public WellType getWellType() {
        return wellType;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setWellType(WellType wellType) {
        this.wellType = wellType;
        return this;
    }

    @Generated("generated by IDE")
    public Dose getDose() {
        return dose;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setDose(Dose dose) {
        this.dose = dose;
        return this;
    }

    @Generated("generated by IDE")
    public Double getDilutionFactor() {
        return dilutionFactor;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setDilutionFactor(Double dilutionFactor) {
        this.dilutionFactor = dilutionFactor;
        return this;
    }

    @Generated("generated by IDE")
    public Integer getReplicates() {
        return replicates;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setReplicates(Integer replicates) {
        this.replicates = replicates;
        return this;
    }

    @Generated("generated by IDE")
    public List<Dose> getDoses() {
        return doses;
    }

    public void increment() {
        this.count = count + 1;
    }

    @Generated("generated by IDE")
    public WellLabelMapping setDoses(List<Dose> doses) {
        this.doses = doses;
        return this;
    }
}
