package edu.harvard.we99.domain;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * A Well is a physical vessel within a Plate or PlateTemplate. It can receive
 * multiple doses of compounds. Our system of plates are rectangluar so
 * a Well has a simple row,col style Coordinate to identify it within a plate.
 *
 * @author mford
 */
public class Well extends AbstractWell<Well> {

    /**
     * The contents of a well are one or more Doses of a compound
     */
    private Set<Dose> contents = new LinkedHashSet<>();

    public Well() {}

    public Well(int row, int col) {
        super(row,col);
    }

    public Well(Coordinate coordinate) {
        super(coordinate);
    }

    /**
     * Adds all of the doses in the array into our well.
     * @param doses
     * @return
     */
    public Well dose(Dose...doses) {
        contents.addAll(Arrays.asList(doses));
        return this;
    }

    @Generated(value = "generated by IDE")
    public Set<Dose> getContents() {
        return contents;
    }

    @Generated(value = "generated by IDE")
    public void setContents(Set<Dose> contents) {
        this.contents = contents;
    }
}

