package edu.harvard.we99.security;

import org.springframework.security.core.userdetails.User;

import javax.annotation.Generated;
import java.util.ArrayList;

/**
 * Subclass of Spring's User class which adds a salt field. For some unknown
 * reason, the spring class doesn't have a suitable field for us to use. It looks
 * like the default behavior there is to use the Username which isn't a good idea
 * since it's likely a known value and thus presents an easier attack vector.
 */
public class SaltyUser extends User {

    /**
     * A per-user salt value that is used by Spring Security to salt the submitted
     * password before SHA-256 encoding it and testing against the value in this
     * bean.
     */
    private final String salt;

    public SaltyUser(String username, String password, String salt) {
        super(username, password, new ArrayList<>());
        this.salt = salt;
    }

    @Generated(value = "generated by IDE")
    public String getSalt() {
        return salt;
    }
}
