package edu.harvard.we99.domain.lists;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import java.util.ArrayList;
import java.util.List;

/**
 * @author mford
 */
@XmlAccessorType(XmlAccessType.FIELD)
public abstract class AbstractList<T> {

    private Long totalCount;
    private int page;

    private List<T> values = new ArrayList<>();

    public AbstractList(Long totalCount, int page, List<T> values) {
        this.values.addAll(values);
        this.totalCount = totalCount;
        this.page = page;
    }

    public AbstractList() {
    }

    public int size() {return values.size();}

    @Generated(value = "generated by IDE")
    public List<T> getValues() {
        return values;
    }

    @Generated(value = "generated by IDE")
    public void setValues(List<T> values) {
        this.values = values;
    }

    @Generated(value = "generated by IDE")
    public int getPage() {
        return page;
    }

    @Generated(value = "generated by IDE")
    public void setPage(int page) {
        this.page = page;
    }

    @Generated(value = "generated by IDE")
    public Long getTotalCount() {
        return totalCount;
    }

    @Generated(value = "generated by IDE")
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }
}
