package edu.harvard.we99.domain;

import javax.annotation.Generated;
import java.util.List;

/**
 * @author mford
 */
public class PermissionMapping {
    private String permission;
    private List<String> roles;

    @Generated(value = "generated by IDE")
    public String getPermission() {
        return permission;
    }

    @Generated(value = "generated by IDE")
    public void setPermission(String permission) {
        this.permission = permission;
    }

    @Generated(value = "generated by IDE")
    public List<String> getRoles() {
        return roles;
    }

    @Generated(value = "generated by IDE")
    public void setRoles(List<String> roles) {
        this.roles = roles;
    }
}
