package edu.harvard.we99.domain;

import javax.annotation.Generated;

/**
 * @author mford
 */
public class UserMapping {
    private String email;
    private String firstName;
    private String lastName;
    private String password;
    private String role;

    @Generated(value = "generated by IDE")
    public String getEmail() {
        return email;
    }

    @Generated(value = "generated by IDE")
    public void setEmail(String email) {
        this.email = email;
    }

    @Generated(value = "generated by IDE")
    public String getFirstName() {
        return firstName;
    }

    @Generated(value = "generated by IDE")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Generated(value = "generated by IDE")
    public String getLastName() {
        return lastName;
    }

    @Generated(value = "generated by IDE")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Generated(value = "generated by IDE")
    public String getPassword() {
        return password;
    }

    @Generated(value = "generated by IDE")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value = "generated by IDE")
    public String getRole() {
        return role;
    }

    @Generated(value = "generated by IDE")
    public void setRole(String role) {
        this.role = role;
    }
}
