package edu.harvard.we99.domain;

import org.joda.time.DateTime;

import javax.annotation.Generated;

/**
 * @author alan orcharton
 */
public class DrPlateResultMapping {


    @Generated("generated by IDE")
    public void setPlateBarcode(String plateBarcode) {
        this.plateBarcode = plateBarcode;
    }

    private String plateBarcode;
    private int row;
    private int col;
    private Double value;
    private String label;
    private String measuredAt;

    @Generated("generated by IDE")
    public int getRow() {
        return row;
    }

    @Generated("generated by IDE")
    public void setRow(int row) {
        this.row = row;
    }

    @Generated("generated by IDE")
    public int getCol() {
        return col;
    }

    @Generated("generated by IDE")
    public void setCol(int col) {
        this.col = col;
    }

    @Generated("generated by IDE")
    public Double getValue() {
        return value;
    }

    @Generated("generated by IDE")
    public void setValue(Double value) {
        this.value = value;
    }

    @Generated("generated by IDE")
    public String getLabel() {
        return label;
    }

    @Generated("generated by IDE")
    public void setLabel(String label) {
        this.label = label;
    }

    @Generated("generated by IDE")
    public String getMeasuredAt() {
        return measuredAt;
    }

    @Generated("generated by IDE")
    public void setMeasuredAt(String measuredAt) {
        this.measuredAt = measuredAt;
    }

    @Generated("generated by IDE")
    public String getPlateBarcode() {
        return plateBarcode;
    }
}
