package edu.harvard.we99.config;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

/**
 * Config bean for sending emails
 *
 * @author mford
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class EmailConfig {
    /**
     * The SMTP host that delivers the message
     */
    private String host = "smtp.gmail.com";
    /**
     * The port for the host. Likely 587 since we're assuming TLS enabled
     */
    private int port = 587;
    /**
     * Username for authenticating to the host. For gmail, this is your email addy
     */
    private String username  = "we99.2015@gmail.com";
    /**
     * Password for authenticating to the host. For gmail, this is your email pw
     */
    private String password;
    /**
     * The from address to use when delivering messages.
     */
    private String from = "we99.2015@gmail.com";

    public EmailConfig() {}

    @Generated(value = "generated by IDE")
    public String getHost() {
        return host;
    }

    @Generated(value = "generated by IDE")
    public String getPassword() {
        return password;
    }

    @Generated(value = "generated by IDE")
    public int getPort() {
        return port;
    }

    @Generated(value = "generated by IDE")
    public String getUsername() {
        return username;
    }

    @Generated(value = "generated by IDE")
    public String getFrom() {
        return from;
    }

    @Generated(value = "generated by IDE")
    public void setFrom(String from) {
        this.from = from;
    }

    @Generated(value = "generated by IDE")
    public void setHost(String host) {
        this.host = host;
    }

    @Generated(value = "generated by IDE")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value = "generated by IDE")
    public void setPort(int port) {
        this.port = port;
    }

    @Generated(value = "generated by IDE")
    public void setUsername(String username) {
        this.username = username;
    }
}
