package edu.harvard.we99.services.io;

import edu.harvard.we99.domain.Plate;
import edu.harvard.we99.domain.results.PlateResult;

import javax.annotation.Generated;

/**
 * @author markford
 */
public class PlateWithOptionalResults {
    private final Plate plate;
    private PlateResult results;

    public PlateWithOptionalResults(Plate plate) {
        this.plate = plate;
    }

    @Generated("generated by IDE")
    public Plate getPlate() {
        return plate;
    }

    @Generated("generated by IDE")
    public PlateResult getResults() {
        return results;
    }

    @Generated("generated by IDE")
    public PlateWithOptionalResults setResults(PlateResult results) {
        this.results = results;
        return this;
    }
}
