package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.Coordinate;
import edu.harvard.we99.domain.PlateDimension;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PersistenceException;
import javax.validation.constraints.NotNull;
import java.util.Set;

/**
 * @author mford
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class AbstractPlateEntity<T extends AbstractPlateEntity> {
    /**
     * Primary key field is auto generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name provided by the user must be unique within the db
     */
    @NotNull
    @Column(unique = true)
    private String name;

    /**
     * Optional user provided description
     */
    @Column(length = 1024)
    private String description;

    /**
     * Every plate has a plate type that identifies its size, orientation, and manufacturer.
     * There may be 100's of these plate types in the system
     */
    @ManyToOne
    @NotNull @JoinColumn(updatable = false)
    private PlateTypeEntity plateType;

    /**
     * Validation check that we don't have an invalid coordinate for a Well that
     * cannot exist within this plate based on its plate type.
     */
    protected void checkWells(Set<Coordinate> coords) {
        // get the max row and max col
        if (getPlateType() != null) {
            // note: checking for plateType != null to avoid a NPE as we're only
            // interested in validating the well coordinates here. The EntityManager
            // will handle the validation that we actually have a PlateType,
            // although after this call.
            int maxRow = 0;
            int maxCol = 0;
            for(Coordinate coord : coords) {
                maxRow = Math.max(maxRow, coord.getRow());
                maxCol = Math.max(maxCol, coord.getCol());
            }

            PlateDimension maxSpecified = new PlateDimension(maxRow, maxCol);

            if (!getPlateType().getDim().greaterThan(maxSpecified)) {
                String message = "Coordinates for wells must be with 0x0 and %dx%d";
                String formattedErrorMessage = String.format(
                        message, getPlateType().getDim().getRows(), getPlateType().getDim().getCols());
                throw new PersistenceException(formattedErrorMessage);
            }
        }
    }

    @Generated(value = "generated by IDE")
    public String getDescription() {
        return description;
    }

    @Generated(value = "generated by IDE")
    public void setDescription(String description) {
        this.description = description;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity getPlateType() {
        return plateType;
    }

    @Generated(value = "generated by IDE")
    public void setPlateType(PlateTypeEntity plateType) {
        this.plateType = plateType;
    }

    @Generated(value = "generated by IDE")
    public T withDescription(final String description) {
        this.description = description;
        return (T) this;
    }

    @Generated(value = "generated by IDE")
    public T withId(final Long id) {
        this.id = id;
        return (T) this;
    }

    @Generated(value = "generated by IDE")
    public T withName(final String name) {
        this.name = name;
        return (T) this;
    }

    @Generated(value = "generated by IDE")
    public T withPlateType(final PlateTypeEntity plateType) {
        this.plateType = plateType;
        return (T) this;
    }
}
