package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.FitEquation;

import javax.annotation.Generated;
import javax.persistence.*;
import java.util.List;

/**
 * @author alan orcharton
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class AbstractFitParameterEntity <T extends AbstractFitParameterEntity> {

    /**
     * Primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private FitEquation fitEquation = FitEquation.HILLEQUATION;


    @OneToMany(cascade = CascadeType.PERSIST)
    private List<DoseResponseResultEntity> associatedDoseResponses;

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public T setId(Long id) {
        this.id = id;
        return (T) this;
    }

    @Generated("generated by IDE")
    public FitEquation getFitEquation() {
        return fitEquation;
    }

    @Generated("generated by IDE")
    public T setFitEquation(FitEquation fitEquation) {
        this.fitEquation = fitEquation;
        return (T) this;
    }
}
