package edu.harvard.we99.services.storage.entities;


import edu.harvard.we99.domain.results.DoseResponseResult;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.annotation.Generated;

/**
 * @author alan orcharton
 */

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class AbstractPointEntity <T extends AbstractPointEntity> {

    /**
     * Primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Double x;
    private Double y;




    @ManyToOne
    protected DoseResponseResultEntity associatedDoseResponseResult;

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public T setId(Long id) {
        this.id = id;
        return (T) this;
    }


    @Generated("generated by IDE")
    public DoseResponseResultEntity getAssociatedDoseResponseResult() {
        return associatedDoseResponseResult;
    }

    @Generated("generated by IDE")
    public T setAssociatedDoseResponseResult(DoseResponseResultEntity associatedDoseResponseResult) {
        this.associatedDoseResponseResult = associatedDoseResponseResult;
        return (T) this;
    }



    @Generated("generated by IDE")
    public Double getX() {
        return x;
    }

    @Generated("generated by IDE")
    public T setX(Double x) {
        this.x = x;
        return (T) this;
    }

    @Generated("generated by IDE")
    public Double getY() {
        return y;
    }

    @Generated("generated by IDE")
    public T setY(Double y) {
        this.y = y;
        return (T) this;
    }
}
