package edu.harvard.we99.services.storage.entities;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entity for a named compound within our domain
 *
 * @author mford
 */
@Entity
@Table(name = "compounds")
public class CompoundEntity {
    /**
     * Primary key is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Compound names must be unique within our system
     */
    @Column(unique = true)
    private String name;

    public CompoundEntity() {}

    public CompoundEntity(Long id, String name) {
        this.name = name;
        this.id = id;
    }

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public CompoundEntity setId(Long id) {
        this.id = id;
        return this;
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public CompoundEntity setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    @Generated(value = "generated by IDE")
    public String toString() {
        return "CompoundEntity{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
