package edu.harvard.we99.services.storage.entities;


import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * @author alan orcharton
 */
@Entity
@Table(name = "curvefitpoints")
public class CurveFitPointEntity extends AbstractPointEntity<CurveFitPointEntity> {


    private Integer sequenceNumber;

    public CurveFitPointEntity() {}

    public CurveFitPointEntity(Integer sequenceNumber){
        super();
        this.sequenceNumber = sequenceNumber;
    }


    @Generated("generated by IDE")
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    @Generated("generated by IDE")
    public CurveFitPointEntity setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }
}
