package edu.harvard.we99.services.storage.entities;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

import edu.harvard.we99.domain.FitEquation;
import edu.harvard.we99.domain.FitParameter;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import java.util.*;

/**
 * @author alan orcharton
 */

@Entity
@Table(name = "doseresponseresults")
public class DoseResponseResultEntity {

    /**
     * Primary key files is auto generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long Id;

    /**
     * Creation time
     */
    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(updatable = false)
    private DateTime created;


    /**
     * Time of the last modification (computed when the bean is saved
     */
    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    private DateTime lastModified;

    /**
     * Reference to the Experiment
     */
    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(updatable = false)
    @NotNull
    private ExperimentEntity experiment;

    /**
     * Reference to the Compound that the dose response is for
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @NotNull
    private CompoundEntity compound;

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    private Map<Long, WellEntity> doseWells = new HashMap<>();

    @OneToMany
    private List<ExperimentPointEntity> experimentPoints = new ArrayList<>();

    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    private List<CurveFitPointEntity> curveFitPoints = new ArrayList<>();

    @ElementCollection(targetClass = FitParameter.class)
    @CollectionTable(name = "doseresponse_fitparameters", joinColumns = @JoinColumn(name = "doseresponseid"))
    private Map<String,FitParameter> fitParameterMap = new HashMap<>();

    /**
     * Optional comments from the user about this plate of its changes
     */
    private String comments;

    private FitEquation fitEquation = FitEquation.HILLEQUATION;


    public void addWell(Long id, WellEntity we){
        doseWells.put(id, we);
    }

    /**
     * Adds a new Experiment point - results for a well
     * @param epe Entity to add the point to
     */
    public void addExperimentPoint(ExperimentPointEntity epe) { experimentPoints.add(epe);}

    /**
     * Adds a new curve fit point - result of curve fit
     * @param cfe The point entity to be added
     */
    public void addCurveFitPoint(CurveFitPointEntity cfe) {
        curveFitPoints.add(cfe);
    }


    public void addFitParameter(FitParameter parameter) {
        fitParameterMap.put(parameter.getName(), parameter);
    }

    @Generated("generated by IDE")
    public String getComments() {
        return comments;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setComments(String comments) {
        this.comments = comments;
        return this;
    }


    @Generated("generated by IDE")
    public Long getId() {
        return Id;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setId(Long id) {
        Id = id;
        return this;
    }

    @Generated("generated by IDE")
    public DateTime getCreated() {
        return created;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setCreated(DateTime created) {
        this.created = created;
        return this;
    }

    @Generated("generated by IDE")
    public DateTime getLastModified() {
        return lastModified;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setLastModified(DateTime lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    @Generated("generated by IDE")
    public CompoundEntity getCompound() {
        return compound;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setCompound(CompoundEntity compound) {
        this.compound = compound;
        return this;
    }

    @Generated("generated by IDE")
    public Map<Long, WellEntity> getDoseWells() {
        return doseWells;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setDoseWells(Map<Long, WellEntity> doseWells) {
        this.doseWells = doseWells;
        return this;
    }

    @Generated("generated by IDE")
    public List<ExperimentPointEntity> getExperimentPoints() {
        return experimentPoints;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setExperimentPoints(List<ExperimentPointEntity> experimentPoints) {
        this.experimentPoints = experimentPoints;
        return this;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setExperiment(ExperimentEntity experiment) {
        this.experiment = experiment;
        return this;
    }

    @Generated("generated by IDE")
    public ExperimentEntity getExperiment() {
        return experiment;
    }

    @Generated("generated by IDE")
    public List<CurveFitPointEntity> getCurveFitPoints() {
        return curveFitPoints;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setCurveFitPoints(List<CurveFitPointEntity> curveFitPoints) {
        this.curveFitPoints = curveFitPoints;
        return this;
    }

    @Generated("generated by IDE")
    public Map<String,FitParameter> getFitParameterMap() {
        return fitParameterMap;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setFitParameterMap(Map<String,FitParameter> fitParameterMap) {
        this.fitParameterMap = fitParameterMap;
        return this;
    }

    @Generated("generated by IDE")
    public FitEquation getFitEquation() {
        return fitEquation;
    }

    @Generated("generated by IDE")
    public DoseResponseResultEntity setFitEquation(FitEquation fitEquation) {
        this.fitEquation = fitEquation;
        return this;
    }
}
