package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.Compound;
import edu.harvard.we99.domain.ExperimentPoint;
import edu.harvard.we99.domain.Plate;
import edu.harvard.we99.domain.Well;

import javax.annotation.Generated;
import javax.persistence.*;

/**
 * @author alan orcharton
 */
@Entity
@Table(name = "experimentpoints")
public class ExperimentPointEntity extends AbstractPointEntity<ExperimentPointEntity>{



    @OneToOne
    private PlateEntity associatedPlate;

    @OneToOne
    private WellEntity associatedWell;





    public ExperimentPointEntity(){}
    public ExperimentPointEntity(PlateEntity plate, WellEntity well){
        super();
        this.associatedPlate = plate;
        this.associatedWell = well;
    }

    @Generated("generated by IDE")
    public WellEntity getAssociatedWell() {
            return associatedWell;
        }

    @Generated("generated by IDE")
    public ExperimentPointEntity setAssociatedWell(WellEntity associatedWell) {
            this.associatedWell = associatedWell;
            return this;
    }


    @Generated("generated by IDE")
    public PlateEntity getAssociatedPlate() {
            return associatedPlate;
        }

    @Generated("generated by IDE")
    public ExperimentPointEntity setAssociatedPlate(PlateEntity associatedPlate) {
        this.associatedPlate = associatedPlate;
        return this;
    }

}
