package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.ExperimentStatus;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * @author mford
 */
@Entity
@Table(name = "experiments")
public class ExperimentEntity {
    /**
     * The primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User provided name for the experiment
     */
    @NotNull
    private String name;

    private String description;

    @NotNull
    private ExperimentStatus status = ExperimentStatus.UNPUBLISHED;

    /**
     * Datetime for the creation of the experiment
     */
    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(updatable = false)
    private DateTime created;

    /**
     * Reference to the protocol that governs this experiment
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @NotNull
    private ProtocolEntity protocol;

    /**
     * Users that are permitted to view/modify data for this Experiment
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @MapKey(name = "email")
    private Map<String,UserEntity> members = new HashMap<>();

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    private Set<LabelEntity> labels = new HashSet<>();

    @OneToMany(orphanRemoval = true, fetch = FetchType.LAZY, mappedBy = "experiment", cascade = CascadeType.PERSIST)
    @OrderBy("created")
    private List<PlateEntity> plates = new ArrayList<>();

    @OneToMany(orphanRemoval = true, fetch = FetchType.LAZY, mappedBy = "experiment")
    private Set<DoseResponseResultEntity> doseResponseResults = new HashSet<>();

    public ExperimentEntity() {}

    public ExperimentEntity(String name) {
        this.name = name;
    }

    @PrePersist
    private void prePersist() {
        this.created = DateTime.now();
    }

    public void addUser(UserEntity user) {
        members.put(user.getEmail(), user);
    }

    public void removeUser(UserEntity user) {
        members.remove(user.getEmail());
    }

    @Generated("generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setId(Long id) {
        this.id = id;
        return this;
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setName(String name) {
        this.name = name;
        return this;
    }

    @Generated("generated by IDE")
    public String getDescription() {
        return description;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setDescription(String description) {
        this.description = description;
        return this;
    }

    @Generated("generated by IDE")
    public ExperimentStatus getStatus() {
        return status;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setStatus(ExperimentStatus status) {
        this.status = status;
        return this;
    }

    @Generated("generated by IDE")
    public DateTime getCreated() {
        return created;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setCreated(DateTime created) {
        this.created = created;
        return this;
    }

    @Generated("generated by IDE")
    public ProtocolEntity getProtocol() {
        return protocol;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setProtocol(ProtocolEntity protocol) {
        this.protocol = protocol;
        return this;
    }

    @Generated("generated by IDE")
    public Map<String, UserEntity> getMembers() {
        return members;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setMembers(Map<String, UserEntity> members) {
        this.members = members;
        return this;
    }

    @Generated("generated by IDE")
    public Set<LabelEntity> getLabels() {
        return labels;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setLabels(Set<LabelEntity> labels) {
        this.labels = labels;
        return this;
    }

    @Generated("generated by IDE")
    public List<PlateEntity> getPlates() {
        return plates;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setPlates(List<PlateEntity> plates) {
        this.plates = plates;
        return this;
    }

    @Generated("generated by IDE")
    public Set<DoseResponseResultEntity> getDoseResponseResults() {
        return doseResponseResults;
    }

    @Generated("generated by IDE")
    public ExperimentEntity setDoseResponseResults(Set<DoseResponseResultEntity> doseResponseResults) {
        this.doseResponseResults = doseResponseResults;
        return this;
    }
}
