package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.HillFitParameter;
import edu.harvard.we99.domain.ParameterStatus;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author alan orcharton
 */
@Entity
@Table(name = "hillfitparameter")
public class HillFitParameterEntity extends AbstractFitParameterEntity<HillFitParameterEntity>  {

    private Double top;
    private Double bottom;
    private Double logEC50;
    private Double slope;

    private ParameterStatus topStatus = ParameterStatus.FLOAT;
    private ParameterStatus bottomStatus = ParameterStatus.FLOAT;
    private ParameterStatus logEC50Status = ParameterStatus.FLOAT;
    private ParameterStatus slopeStatus = ParameterStatus.FLOAT;

    @Generated("generated by IDE")
    public Double getTop() {
        return top;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setTop(Double top) {
        this.top = top;
        return this;
    }

    @Generated("generated by IDE")
    public Double getBottom() {
        return bottom;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setBottom(Double bottom) {
        this.bottom = bottom;
        return this;
    }

    @Generated("generated by IDE")
    public Double getLogEC50() {
        return logEC50;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setLogEC50(Double logEC50) {
        this.logEC50 = logEC50;
        return this;
    }

    @Generated("generated by IDE")
    public Double getSlope() {
        return slope;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setSlope(Double slope) {
        this.slope = slope;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getTopStatus() {
        return topStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setTopStatus(ParameterStatus topStatus) {
        this.topStatus = topStatus;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getBottomStatus() {
        return bottomStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setBottomStatus(ParameterStatus bottomStatus) {
        this.bottomStatus = bottomStatus;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getLogEC50Status() {
        return logEC50Status;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setLogEC50Status(ParameterStatus logEC50Status) {
        this.logEC50Status = logEC50Status;
        return this;
    }

    @Generated("generated by IDE")
    public ParameterStatus getSlopeStatus() {
        return slopeStatus;
    }

    @Generated("generated by IDE")
    public HillFitParameterEntity setSlopeStatus(ParameterStatus slopeStatus) {
        this.slopeStatus = slopeStatus;
        return this;
    }
}
