package edu.harvard.we99.services.storage.entities;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author mford
 */
@Entity
@Table(name = "labels")
public class LabelEntity {
    /**
     * The primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    private String name;

    private String value;

    public LabelEntity() {}

    public LabelEntity(String name) {
        this.name = name;
    }

    public LabelEntity(String name, String value) {
        this.name = name;
        this.value = value;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public String getValue() {
        return value;
    }

    @Generated(value = "generated by IDE")
    public void setValue(String value) {
        this.value = value;
    }
}
