package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.PlateDimension;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author mford
 */
@Entity
@Table(name = "platetypes")
public class PlateTypeEntity {
    /**
     * The primary key for this entity is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * name of the plate
     */
    @NotNull
    @Column(unique = true)
    private String name;

    /**
     * Optional description for the plate.
     */
    private String description;

    @Embedded
    @NotNull
    private PlateDimension dim;

    /**
     * The manufacturer of the plate
     */
    @NotNull
    private String manufacturer;

    /**
     * Link to the manufacturer's website to order plates of this type.
     */
    private String orderLink;

    @Generated(value = "generated by IDE")
    public String getDescription() {
        return description;
    }

    @Generated(value = "generated by IDE")
    public void setDescription(String description) {
        this.description = description;
    }

    @Generated(value = "generated by IDE")
    public PlateDimension getDim() {
        return dim;
    }

    @Generated(value = "generated by IDE")
    public void setDim(PlateDimension dim) {
        this.dim = dim;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getOrderLink() {
        return orderLink;
    }

    @Generated(value = "generated by IDE")
    public void setOrderLink(String orderLink) {
        this.orderLink = orderLink;
    }

    @Generated(value = "generated by IDE")
    public String getManufacturer() {
        return manufacturer;
    }

    @Generated(value = "generated by IDE")
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withDescription(final String description) {
        this.description = description;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withId(final Long id) {
        this.id = id;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withName(final String name) {
        this.name = name;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withDim(final PlateDimension dim) {
        this.dim = dim;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateTypeEntity withLink(final String link) {
        this.orderLink = link;
        return this;
    }
}
