package edu.harvard.we99.services.storage.entities;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author mford
 */
@Entity
public class PlateMetricsEntity {
    /**
     * Primary key field is auto generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String label;
    private Double avgPositive;
    private Double avgNegative;
    private Double zee;
    private Double zeePrime;

    @Generated(value = "generated by IDE")
    public Double getAvgNegative() {
        return avgNegative;
    }

    @Generated(value = "generated by IDE")
    public void setAvgNegative(Double avgNegative) {
        this.avgNegative = avgNegative;
    }

    @Generated(value = "generated by IDE")
    public Double getAvgPositive() {
        return avgPositive;
    }

    @Generated(value = "generated by IDE")
    public void setAvgPositive(Double avgPositive) {
        this.avgPositive = avgPositive;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getLabel() {
        return label;
    }

    @Generated(value = "generated by IDE")
    public void setLabel(String label) {
        this.label = label;
    }

    @Generated(value = "generated by IDE")
    public Double getZee() {
        return zee;
    }

    @Generated(value = "generated by IDE")
    public void setZee(Double zee) {
        this.zee = zee;
    }

    @Generated(value = "generated by IDE")
    public Double getZeePrime() {
        return zeePrime;
    }

    @Generated(value = "generated by IDE")
    public void setZeePrime(Double zeePrime) {
        this.zeePrime = zeePrime;
    }
}
