package edu.harvard.we99.services.storage.entities;

import edu.harvard.we99.domain.Coordinate;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * @author mford
 */
@Entity
@Table(name = "plates")
public class PlateEntity extends AbstractPlateEntity<PlateEntity> {
    /**
     * Reference to the id of the PlateTemplate that this Plate was derived from.
     *
     * It's odd to have a Long here but I worry about referring back to the
     * PlateTemplate entity since it could change over time and make a previous
     * instance of a Plate inconsistent since the size might not match.
     */
    @Column(updatable = false)
    private Long derivedFrom;

    /**
     * Optional user provided barcode for the plate
     */
    private String barcode;

    /**
     * A plate consists of Wells in which the compounds we want to test are placed.
     * Each well is uniquely identified by a row,col coordinate within this plate
     * so we'll store them according to their coordinate.
     */
    @OneToMany(orphanRemoval = true, cascade = CascadeType.PERSIST)
    @Size(min = 0)
    @MapKey(name="coordinate")
    private Map<Coordinate, WellEntity> wells = new LinkedHashMap<>();

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(updatable = false)
    @NotNull
    private ExperimentEntity experiment;

    @PrePersist
    @PreUpdate
    private void validate() {
        checkWells(wells.keySet());
    }

    @Generated(value = "generated by IDE")
    public String getBarcode() {
        return barcode;
    }

    @Generated(value = "generated by IDE")
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    @Generated(value = "generated by IDE")
    public Long getDerivedFrom() {
        return derivedFrom;
    }

    @Generated(value = "generated by IDE")
    public void setDerivedFrom(Long derivedFrom) {
        this.derivedFrom = derivedFrom;
    }

    @Generated(value = "generated by IDE")
    public ExperimentEntity getExperiment() {
        return experiment;
    }

    @Generated(value = "generated by IDE")
    public void setExperiment(ExperimentEntity experiment) {
        this.experiment = experiment;
    }

    @Generated(value = "generated by IDE")
    public Map<Coordinate, WellEntity> getWells() {
        return wells;
    }

    @Generated(value = "generated by IDE")
    public void setWells(Map<Coordinate, WellEntity> wells) {
        this.wells = wells;
    }

    @Generated(value = "generated by IDE")
    public PlateEntity withBarcode(final String barcode) {
        this.barcode = barcode;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateEntity withDerivedFrom(final Long derivedFrom) {
        this.derivedFrom = derivedFrom;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateEntity withExperiment(final ExperimentEntity experiment) {
        this.experiment = experiment;
        return this;
    }

    @Generated(value = "generated by IDE")
    public PlateEntity withWells(final Map<Coordinate, WellEntity> wells) {
        this.wells = wells;
        return this;
    }

    public PlateEntity withWells(WellEntity...wells) {
        for(WellEntity we : wells) {
            this.wells.put(we.getCoordinate(), we);
        }
        return this;
    }

    public void addWell(WellEntity w) {
        this.wells.put(w.getCoordinate(), w);
    }
}
