package edu.harvard.we99.services.storage.entities;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;

/**
 * @author markford
 */
@Entity
@Table(name = "versionInfo")
public class VersionEntity {

    public enum Names {DATABASE}

    @Id
    private String name;
    private String version;
    /**
     * Datetime for the creation of the experiment
     */
    @Type(type="org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    @Column(updatable = false)
    private DateTime created;

    public VersionEntity() {}

    public VersionEntity(Names name, String version) {
        this.name = name.name();
        this.version = version;
    }

    @PrePersist
    private void prePersist() {
        this.created = DateTime.now();
    }

    @Generated("generated by IDE")
    public String getName() {
        return name;
    }

    @Generated("generated by IDE")
    public VersionEntity setName(String name) {
        this.name = name;
        return this;
    }

    @Generated("generated by IDE")
    public String getVersion() {
        return version;
    }

    @Generated("generated by IDE")
    public VersionEntity setVersion(String version) {
        this.version = version;
        return this;
    }

    @Generated("generated by IDE")
    public DateTime getCreated() {
        return created;
    }
}
