package edu.harvard.we99.security;

import javax.annotation.Generated;

/**
 * Config bean for sending emails
 *
 * @author mford
 */
public class EmailConfig {
    /**
     * The SMTP host that delivers the message
     */
    private final String host;
    /**
     * The port for the host. Likely 587 since we're assuming TLS enabled
     */
    private final int port;
    /**
     * Username for authenticating to the host. For gmail, this is your email addy
     */
    private final String username;
    /**
     * Password for authenticating to the host. For gmail, this is your email pw
     */
    private final String password;
    /**
     * The from address to use when delivering messages.
     */
    private final String from;

    public EmailConfig(String host, int port, String username, String password, String from) {
        this.host = host;
        this.port = port;
        this.username = username;
        this.from = from;
        this.password = password;
    }

    @Generated(value = "generated by IDE")
    public String getHost() {
        return host;
    }

    @Generated(value = "generated by IDE")
    public String getPassword() {
        return password;
    }

    @Generated(value = "generated by IDE")
    public int getPort() {
        return port;
    }

    @Generated(value = "generated by IDE")
    public String getUsername() {
        return username;
    }

    @Generated(value = "generated by IDE")
    public String getFrom() {
        return from;
    }
}
