package edu.harvard.we99.security;

import edu.harvard.we99.domain.BaseEntity;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * Models a permission in the system. The separation of Roles and Permissions
 * means a more flexible security configuration as system admins could conceivably
 * customize the permissions mapped to a given role. This allows the services
 * to have statically permission requirements while the Roles themselves can
 * be dynamic.
 *
 * @author mford
 */
@Entity
@Table(uniqueConstraints = {@UniqueConstraint( columnNames = {"name"})})
public class Permission extends BaseEntity {
    /**
     * Primary key is generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(updatable = false)
    private String name;

    public Permission() {}

    public Permission(String name) {
        this.name = name;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getName() {
        return name;
    }

    @Generated(value = "generated by IDE")
    public void setName(String name) {
        this.name = name;
    }
}
