package edu.harvard.we99.security;

import edu.harvard.we99.domain.BaseEntity;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import java.util.HashSet;
import java.util.Set;

/**
 * Models a user in the system. We're not currently using Roles but if we do then
 * we can add them as needed.
 *
 * @author mford
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class User extends BaseEntity {

    private Long id;

    /**
     * We'll use the user's email for communication and their login
     */
    @NotNull
    private String email;

    /**
     * User's first name
     */
    @NotNull
    private String firstName;

    /**
     * User's last name
     */
    @NotNull
    private String lastName;

    @NotNull
    private Role role;

    /**
     * Plain text password provided by the user when they're changing their
     * password. Not otherwise populated.
     */
    private String password;

    /**
     * Value used to salt the user's password. Only here so we can access the salt
     * for the purposes of recomputing their password hash at login. This value
     * doesn't propagate to the client or back to the entity.
     */
    @XmlTransient
    private String salt;

    /**
     * Set of experiment id's that this User has access to. This is is only used
     * server side for authorization purposes.
     */
    @XmlTransient
    private Set<Long> experiments = new HashSet<>();

    @SuppressWarnings("UnusedDeclaration")
    public User() {}

    public User(String emailAddress, String firstName, String lastName) {
        this.email = emailAddress;
        this.firstName = firstName;
        this.lastName = lastName;
    }


    @Generated(value = "generated by IDE")
    public String getEmail() {
        return email;
    }

    @Generated(value = "generated by IDE")
    public void setEmail(String email) {
        this.email = email;
    }

    @Generated(value = "generated by IDE")
    public String getFirstName() {
        return firstName;
    }

    @Generated(value = "generated by IDE")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Generated(value = "generated by IDE")
    public Long getId() {
        return id;
    }

    @Generated(value = "generated by IDE")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "generated by IDE")
    public String getLastName() {
        return lastName;
    }

    @Generated(value = "generated by IDE")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Generated(value = "generated by IDE")
    public Role getRole() {
        return role;
    }

    @Generated(value = "generated by IDE")
    public void setRole(Role role) {
        this.role = role;
    }

    @Generated(value = "generated by IDE")
    public String getPassword() {
        return password;
    }

    @Generated(value = "generated by IDE")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value = "generated by IDE")
    public User withEmail(final String email) {
        this.email = email;
        return this;
    }

    @Generated(value = "generated by IDE")
    public User withId(final Long id) {
        this.id = id;
        return this;
    }

    @Generated(value = "generated by IDE")
    public User withFirstName(final String firstName) {
        this.firstName = firstName;
        return this;
    }

    @Generated(value = "generated by IDE")
    public User withLastName(final String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Generated(value = "generated by IDE")
    public User withRole(final Role role) {
        this.role = role;
        return this;
    }

    @Generated(value = "generated by IDE")
    public User withPassword(final String password) {
        this.password = password;
        return this;
    }

    @Generated(value = "generated by IDE")
    public String getSalt() {
        return salt;
    }

    @Generated(value = "generated by IDE")
    public void setSalt(String salt) {
        this.salt = salt;
    }

    @Generated(value = "generated by IDE")
    public Set<Long> getExperiments() {
        return experiments;
    }

    @Generated(value = "generated by IDE")
    public void setExperiments(Set<Long> experiments) {
        this.experiments = experiments;
    }

    public boolean isMember(Long experimentId) {
        return experiments.contains(experimentId);
    }
}
