package edu.harvard.we99.util;

import com.fasterxml.jackson.jaxrs.cfg.Annotations;
import com.fasterxml.jackson.jaxrs.json.JacksonJaxbJsonProvider;
import org.apache.cxf.jaxrs.client.Client;
import org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean;

import javax.annotation.Generated;
import javax.ws.rs.core.MediaType;
import java.net.URL;

/**
 * Wrapper around the CXF factory that presents an interface for any REST
 * service deployed at the container targeted by the URL passed in the ctor.
 *
 * @author mford
 */
public class ClientFactory {
    /**
     * URL to the JAXRS container.
     */
    private final URL address;

    /**
     * Optional username to use in the underlying HTTP auth challenge
     */
    private final String username;

    /**
     * Optional password to use in the underlying HTTP auth challenge
     */
    private final String password;

    /**
     * media type to use for the request.
     *
     * Needed to add this in order to support the specification of form encoded params.
     */
    private MediaType mediaType = MediaType.APPLICATION_JSON_TYPE;

    public ClientFactory(URL address, String username, String password) {
        this.address = address;
        this.username = username;
        this.password = password;
    }

    public <T> T create(Class<T> serviceClass) {
        JAXRSClientFactoryBean factory = new JAXRSClientFactoryBean();
        factory.setAddress(address.toExternalForm());
        factory.setServiceClass(serviceClass);
        factory.setUsername(username);
        factory.setPassword(password);
        JacksonJaxbJsonProvider provider = new JacksonJaxbJsonProvider(
                JacksonUtil.getObjectMapper(),
                new Annotations[]{Annotations.JACKSON, Annotations.JAXB});
        factory.setProvider(provider);
        final Client client = factory.create();
        client.type(mediaType);
        client.accept(MediaType.APPLICATION_JSON_TYPE);
        return serviceClass.cast(client);
    }

    @Generated(value = "generated by IDE")
    public MediaType getMediaType() {
        return mediaType;
    }

    @Generated(value = "generated by IDE")
    public void setMediaType(MediaType mediaType) {
        this.mediaType = mediaType;
    }
}